support for eip191
Zondax/ledger-sei pull request #7
Opened 2024-11-27 17:51 UTC by 0xPxt

2024-11-27 19:50 UTC, neithanmo requested changes

2024-11-27 19:50 UTC, neithanmo commented on app/src/evm/evm_eip191.c
> +static void eip191_uint32_to_str(uint32_t num, char *str) {
No need to implement it from scratch, we have functions in [ledger-zxlib](https://github.com/Zondax/ledger-zxlib/blob/main/include/zxformat.h#L27) for that conversion



so `uint32_to_str` generated by the macro and full tested and used in other apps

2024-11-27 19:50 UTC, neithanmo commented on app/src/evm/evm_eip191.c
> +    CHECK_CX_OK(cx_hash_no_throw((cx_hash_t *)&sha3, 0, (uint8_t *)SIGN_MAGIC, sizeof(SIGN_MAGIC) - 1, NULL, 0));
you should not do  `sizeof(SIGN_MAGIC) - 1`
because the standard says that the _null terminator_ character must be included and hashed

2024-11-27 19:50 UTC, neithanmo commented on app/src/evm/evm_eip191.c
> +    CHECK_CX_OK(cx_hash_no_throw((cx_hash_t *)&sha3, 0, (uint8_t *)SIGN_MAGIC, sizeof(SIGN_MAGIC) - 1, NULL, 0));
can you double check that in the eip191 spec?

2024-11-29 07:30 UTC, chcmedeiros approved these changes

2024-11-29 07:34 UTC, merged